name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: "bkoral.io"
        username: builder
        password: ${{ secrets.deploypw }}
        script: ls -la
